/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssetType = { 'BTC' : null } |
  { 'ICP' : null };
export interface AuditLog {
  'id' : EntityId,
  'action' : string,
  'userId' : UserId,
  'tenantId' : TenantId,
  'entityId' : EntityId,
  'timestamp' : Timestamp,
  'details' : string,
  'entityType' : string,
}
export type AutomationAction = { 'RunPayroll' : null } |
  { 'CreateTask' : null } |
  { 'SendNotification' : null } |
  { 'UpdateStatus' : null };
export interface AutomationRule {
  'id' : EntityId,
  'action' : AutomationAction,
  'trigger' : AutomationTrigger,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
  'isActive' : boolean,
  'tenantId' : TenantId,
}
export type AutomationTrigger = { 'OnTaskStatusChange' : null } |
  { 'OnNoteCreated' : null } |
  { 'OnPaymentDue' : null } |
  { 'Scheduled' : null } |
  { 'OnEscrowUpdate' : null } |
  { 'OnEventReminder' : null };
export interface Backup {
  'id' : EntityId,
  'status' : BackupStatus,
  'completedAt' : [] | [Timestamp],
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'tenantId' : TenantId,
  'backupLabel' : string,
  'sizeBytes' : [] | [bigint],
}
export type BackupStatus = { 'Failed' : null } |
  { 'Running' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface Channel {
  'id' : EntityId,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
  'tenantId' : TenantId,
  'memberIds' : Array<UserId>,
  'isPublic' : boolean,
}
export interface ChannelInput {
  'name' : string,
  'description' : string,
  'memberIds' : Array<UserId>,
  'isPublic' : boolean,
}
export interface CrossLink {
  'linkLabel' : string,
  'tenantId' : TenantId,
  'entityId' : EntityId,
  'entityType' : string,
}
export interface Employee {
  'id' : EntityId,
  'salary' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'email' : string,
  'tenantId' : TenantId,
  'currency' : string,
  'payFrequency' : PayFrequency,
  'lastName' : string,
  'taxRate' : bigint,
  'startDate' : Timestamp,
  'firstName' : string,
}
export interface EmployeeInput {
  'salary' : bigint,
  'userId' : UserId,
  'email' : string,
  'currency' : string,
  'payFrequency' : PayFrequency,
  'lastName' : string,
  'taxRate' : bigint,
  'startDate' : Timestamp,
  'firstName' : string,
}
export type EntityId = string;
export interface EscrowContract {
  'id' : EntityId,
  'status' : EscrowStatus,
  'title' : string,
  'createdAt' : Timestamp,
  'dueDate' : [] | [Timestamp],
  'description' : string,
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'currency' : string,
  'conditions' : Array<string>,
  'crossLinks' : Array<CrossLink>,
  'amount' : bigint,
  'payeeId' : UserId,
  'payerId' : UserId,
}
export interface EscrowInput {
  'title' : string,
  'dueDate' : [] | [Timestamp],
  'description' : string,
  'currency' : string,
  'conditions' : Array<string>,
  'crossLinks' : Array<CrossLink>,
  'amount' : bigint,
  'payeeId' : UserId,
}
export type EscrowStatus = { 'Disputed' : null } |
  { 'Released' : null } |
  { 'Funded' : null } |
  { 'Cancelled' : null } |
  { 'Pending' : null };
export interface Event {
  'id' : EntityId,
  'startTime' : Timestamp,
  'title' : string,
  'endTime' : Timestamp,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
  'attendeeIds' : Array<UserId>,
  'tenantId' : TenantId,
  'recurrence' : RecurrenceRule,
  'updatedAt' : Timestamp,
  'crossLinks' : Array<CrossLink>,
}
export interface EventInput {
  'startTime' : Timestamp,
  'title' : string,
  'endTime' : Timestamp,
  'description' : string,
  'attendeeIds' : Array<UserId>,
  'recurrence' : RecurrenceRule,
  'crossLinks' : Array<CrossLink>,
}
export interface Message {
  'id' : EntityId,
  'content' : string,
  'channelId' : EntityId,
  'createdAt' : Timestamp,
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'replyToId' : [] | [EntityId],
  'crossLinks' : Array<CrossLink>,
  'senderId' : UserId,
}
export interface MessageInput {
  'content' : string,
  'channelId' : EntityId,
  'replyToId' : [] | [EntityId],
  'crossLinks' : Array<CrossLink>,
}
export interface Note {
  'id' : EntityId,
  'title' : string,
  'content' : string,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'crossLinks' : Array<CrossLink>,
}
export interface NoteInput {
  'title' : string,
  'content' : string,
  'tags' : Array<string>,
  'crossLinks' : Array<CrossLink>,
}
export type PayFrequency = { 'BiWeekly' : null } |
  { 'Weekly' : null } |
  { 'Quarterly' : null } |
  { 'Monthly' : null };
export interface PayrollRecord {
  'id' : EntityId,
  'status' : PayrollStatus,
  'period' : string,
  'createdAt' : Timestamp,
  'tenantId' : TenantId,
  'processedAt' : [] | [Timestamp],
  'employeeId' : EntityId,
  'currency' : string,
  'amount' : bigint,
}
export type PayrollStatus = { 'Paused' : null } |
  { 'Active' : null } |
  { 'Completed' : null };
export interface Project {
  'id' : EntityId,
  'status' : ProjectStatus,
  'ownerId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'memberIds' : Array<UserId>,
  'crossLinks' : Array<CrossLink>,
}
export interface ProjectInput {
  'name' : string,
  'description' : string,
  'memberIds' : Array<UserId>,
}
export type ProjectStatus = { 'OnHold' : null } |
  { 'Active' : null } |
  { 'Archived' : null } |
  { 'Completed' : null };
export type RecurrenceRule = { 'Weekly' : null } |
  { 'None' : null } |
  { 'Daily' : null } |
  { 'Monthly' : null } |
  { 'Yearly' : null };
export interface RecurringPayment {
  'id' : EntityId,
  'asset' : AssetType,
  'accountId' : EntityId,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'tenantId' : TenantId,
  'nextRunAt' : Timestamp,
  'frequency' : PayFrequency,
  'toAddress' : string,
  'amount' : bigint,
}
export type Role = { 'Admin' : null } |
  { 'Manager' : null } |
  { 'TeamMember' : null };
export interface Task {
  'id' : EntityId,
  'status' : TaskStatus,
  'title' : string,
  'assigneeId' : [] | [UserId],
  'createdAt' : Timestamp,
  'dueDate' : [] | [Timestamp],
  'description' : string,
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'projectId' : EntityId,
  'priority' : TaskPriority,
  'crossLinks' : Array<CrossLink>,
}
export interface TaskInput {
  'title' : string,
  'assigneeId' : [] | [UserId],
  'dueDate' : [] | [Timestamp],
  'description' : string,
  'projectId' : EntityId,
  'priority' : TaskPriority,
  'crossLinks' : Array<CrossLink>,
}
export type TaskPriority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Critical' : null };
export type TaskStatus = { 'Blocked' : null } |
  { 'Done' : null } |
  { 'Todo' : null } |
  { 'InProgress' : null };
export type TenantId = string;
export type Timestamp = bigint;
export type TransactionStatus = { 'Failed' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export type TransactionType = { 'Stake' : null } |
  { 'Send' : null } |
  { 'Swap' : null } |
  { 'Unstake' : null } |
  { 'Receive' : null };
export type UserId = Principal;
export interface UserProfile {
  'displayName' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : string,
  'tenantId' : TenantId,
  'workspaceId' : EntityId,
}
export interface UserProfileInput {
  'displayName' : string,
  'role' : Role,
  'email' : string,
  'workspaceId' : EntityId,
}
export interface WalletAccount {
  'id' : EntityId,
  'accountId' : string,
  'displayName' : string,
  'btcBalance' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'icpBalance' : bigint,
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'principalId' : string,
}
export interface WalletTransaction {
  'id' : EntityId,
  'status' : TransactionStatus,
  'asset' : AssetType,
  'accountId' : EntityId,
  'fromAddress' : [] | [string],
  'memo' : [] | [string],
  'createdAt' : Timestamp,
  'tenantId' : TenantId,
  'txType' : TransactionType,
  'toAddress' : [] | [string],
  'amount' : bigint,
}
export interface Workspace {
  'id' : EntityId,
  'ownerId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'tenantId' : TenantId,
}
export interface WorkspaceInput { 'name' : string }
export interface _SERVICE {
  'addEmployee' : ActorMethod<
    [TenantId, EmployeeInput],
    { 'ok' : Employee } |
      { 'err' : string }
  >,
  'archiveProject' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : Project } |
      { 'err' : string }
  >,
  'cancelEscrow' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : EscrowContract } |
      { 'err' : string }
  >,
  'cancelRecurringPayment' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : RecurringPayment } |
      { 'err' : string }
  >,
  'createAutomationRule' : ActorMethod<
    [TenantId, string, string, AutomationTrigger, AutomationAction],
    { 'ok' : AutomationRule } |
      { 'err' : string }
  >,
  'createBackup' : ActorMethod<
    [TenantId, string],
    { 'ok' : Backup } |
      { 'err' : string }
  >,
  'createChannel' : ActorMethod<
    [TenantId, ChannelInput],
    { 'ok' : Channel } |
      { 'err' : string }
  >,
  'createEscrow' : ActorMethod<
    [TenantId, EscrowInput],
    { 'ok' : EscrowContract } |
      { 'err' : string }
  >,
  'createEvent' : ActorMethod<
    [TenantId, EventInput],
    { 'ok' : Event } |
      { 'err' : string }
  >,
  'createNote' : ActorMethod<
    [TenantId, NoteInput],
    { 'ok' : Note } |
      { 'err' : string }
  >,
  'createProject' : ActorMethod<
    [TenantId, ProjectInput],
    { 'ok' : Project } |
      { 'err' : string }
  >,
  'createRecurringPayment' : ActorMethod<
    [TenantId, EntityId, string, bigint, AssetType, PayFrequency],
    { 'ok' : RecurringPayment } |
      { 'err' : string }
  >,
  'createTask' : ActorMethod<
    [TenantId, TaskInput],
    { 'ok' : Task } |
      { 'err' : string }
  >,
  'createWalletAccount' : ActorMethod<
    [TenantId, string],
    { 'ok' : WalletAccount } |
      { 'err' : string }
  >,
  'createWorkspace' : ActorMethod<
    [TenantId, WorkspaceInput],
    { 'ok' : Workspace } |
      { 'err' : string }
  >,
  'deactivateEmployee' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : Employee } |
      { 'err' : string }
  >,
  'deleteEvent' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteMessage' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteNote' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteTask' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'disputeEscrow' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : EscrowContract } |
      { 'err' : string }
  >,
  'fundEscrow' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : EscrowContract } |
      { 'err' : string }
  >,
  'getBackup' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : Backup } |
      { 'err' : string }
  >,
  'getChannel' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : Channel } |
      { 'err' : string }
  >,
  'getEmployee' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : Employee } |
      { 'err' : string }
  >,
  'getEscrow' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : EscrowContract } |
      { 'err' : string }
  >,
  'getEvent' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : Event } |
      { 'err' : string }
  >,
  'getMessages' : ActorMethod<
    [TenantId, EntityId, bigint, [] | [Timestamp]],
    Array<Message>
  >,
  'getMyProfile' : ActorMethod<[TenantId], [] | [UserProfile]>,
  'getMyWalletAccount' : ActorMethod<[TenantId], [] | [WalletAccount]>,
  'getNote' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : Note } |
      { 'err' : string }
  >,
  'getProject' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : Project } |
      { 'err' : string }
  >,
  'getTask' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : Task } |
      { 'err' : string }
  >,
  'getWalletAccount' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : WalletAccount } |
      { 'err' : string }
  >,
  'getWorkspace' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : Workspace } |
      { 'err' : string }
  >,
  'getWorkspaceStats' : ActorMethod<
    [TenantId],
    {
      'walletAccountCount' : bigint,
      'employeeCount' : bigint,
      'noteCount' : bigint,
      'escrowCount' : bigint,
      'projectCount' : bigint,
    }
  >,
  'joinChannel' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : Channel } |
      { 'err' : string }
  >,
  'listAuditLogs' : ActorMethod<[TenantId, bigint], Array<AuditLog>>,
  'listAutomationRules' : ActorMethod<[TenantId], Array<AutomationRule>>,
  'listBackups' : ActorMethod<[TenantId], Array<Backup>>,
  'listChannels' : ActorMethod<[TenantId], Array<Channel>>,
  'listEmployees' : ActorMethod<[TenantId], Array<Employee>>,
  'listEscrows' : ActorMethod<[TenantId], Array<EscrowContract>>,
  'listEvents' : ActorMethod<[TenantId, Timestamp, Timestamp], Array<Event>>,
  'listMyEvents' : ActorMethod<[TenantId], Array<Event>>,
  'listNotes' : ActorMethod<[TenantId], Array<Note>>,
  'listPayrollRecords' : ActorMethod<
    [TenantId, [] | [EntityId]],
    Array<PayrollRecord>
  >,
  'listProfiles' : ActorMethod<[TenantId], Array<UserProfile>>,
  'listProjects' : ActorMethod<[TenantId], Array<Project>>,
  'listRecurringPayments' : ActorMethod<
    [TenantId, EntityId],
    Array<RecurringPayment>
  >,
  'listTasks' : ActorMethod<[TenantId, EntityId], Array<Task>>,
  'listTransactions' : ActorMethod<
    [TenantId, EntityId],
    Array<WalletTransaction>
  >,
  'listWorkspaces' : ActorMethod<[TenantId], Array<Workspace>>,
  'processPayroll' : ActorMethod<
    [TenantId, EntityId, string],
    { 'ok' : PayrollRecord } |
      { 'err' : string }
  >,
  'releaseEscrow' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : EscrowContract } |
      { 'err' : string }
  >,
  'searchNotes' : ActorMethod<[TenantId, string], Array<Note>>,
  'sendAsset' : ActorMethod<
    [TenantId, EntityId, AssetType, bigint, string, [] | [string]],
    { 'ok' : WalletTransaction } |
      { 'err' : string }
  >,
  'sendMessage' : ActorMethod<
    [TenantId, MessageInput],
    { 'ok' : Message } |
      { 'err' : string }
  >,
  'toggleAutomationRule' : ActorMethod<
    [TenantId, EntityId],
    { 'ok' : AutomationRule } |
      { 'err' : string }
  >,
  'updateEmployee' : ActorMethod<
    [TenantId, EntityId, EmployeeInput],
    { 'ok' : Employee } |
      { 'err' : string }
  >,
  'updateEvent' : ActorMethod<
    [TenantId, EntityId, EventInput],
    { 'ok' : Event } |
      { 'err' : string }
  >,
  'updateNote' : ActorMethod<
    [TenantId, EntityId, NoteInput],
    { 'ok' : Note } |
      { 'err' : string }
  >,
  'updateProject' : ActorMethod<
    [TenantId, EntityId, ProjectInput],
    { 'ok' : Project } |
      { 'err' : string }
  >,
  'updateTask' : ActorMethod<
    [TenantId, EntityId, TaskInput],
    { 'ok' : Task } |
      { 'err' : string }
  >,
  'upsertProfile' : ActorMethod<
    [TenantId, UserProfileInput],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];