/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TenantId = IDL.Text;
export const UserId = IDL.Principal;
export const PayFrequency = IDL.Variant({
  'BiWeekly' : IDL.Null,
  'Weekly' : IDL.Null,
  'Quarterly' : IDL.Null,
  'Monthly' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const EmployeeInput = IDL.Record({
  'salary' : IDL.Nat,
  'userId' : UserId,
  'email' : IDL.Text,
  'currency' : IDL.Text,
  'payFrequency' : PayFrequency,
  'lastName' : IDL.Text,
  'taxRate' : IDL.Nat,
  'startDate' : Timestamp,
  'firstName' : IDL.Text,
});
export const EntityId = IDL.Text;
export const Employee = IDL.Record({
  'id' : EntityId,
  'salary' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'tenantId' : TenantId,
  'currency' : IDL.Text,
  'payFrequency' : PayFrequency,
  'lastName' : IDL.Text,
  'taxRate' : IDL.Nat,
  'startDate' : Timestamp,
  'firstName' : IDL.Text,
});
export const ProjectStatus = IDL.Variant({
  'OnHold' : IDL.Null,
  'Active' : IDL.Null,
  'Archived' : IDL.Null,
  'Completed' : IDL.Null,
});
export const CrossLink = IDL.Record({
  'linkLabel' : IDL.Text,
  'tenantId' : TenantId,
  'entityId' : EntityId,
  'entityType' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : EntityId,
  'status' : ProjectStatus,
  'ownerId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'memberIds' : IDL.Vec(UserId),
  'crossLinks' : IDL.Vec(CrossLink),
});
export const EscrowStatus = IDL.Variant({
  'Disputed' : IDL.Null,
  'Released' : IDL.Null,
  'Funded' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Pending' : IDL.Null,
});
export const EscrowContract = IDL.Record({
  'id' : EntityId,
  'status' : EscrowStatus,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'dueDate' : IDL.Opt(Timestamp),
  'description' : IDL.Text,
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'currency' : IDL.Text,
  'conditions' : IDL.Vec(IDL.Text),
  'crossLinks' : IDL.Vec(CrossLink),
  'amount' : IDL.Nat,
  'payeeId' : UserId,
  'payerId' : UserId,
});
export const AssetType = IDL.Variant({ 'BTC' : IDL.Null, 'ICP' : IDL.Null });
export const RecurringPayment = IDL.Record({
  'id' : EntityId,
  'asset' : AssetType,
  'accountId' : EntityId,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'tenantId' : TenantId,
  'nextRunAt' : Timestamp,
  'frequency' : PayFrequency,
  'toAddress' : IDL.Text,
  'amount' : IDL.Nat,
});
export const AutomationTrigger = IDL.Variant({
  'OnTaskStatusChange' : IDL.Null,
  'OnNoteCreated' : IDL.Null,
  'OnPaymentDue' : IDL.Null,
  'Scheduled' : IDL.Null,
  'OnEscrowUpdate' : IDL.Null,
  'OnEventReminder' : IDL.Null,
});
export const AutomationAction = IDL.Variant({
  'RunPayroll' : IDL.Null,
  'CreateTask' : IDL.Null,
  'SendNotification' : IDL.Null,
  'UpdateStatus' : IDL.Null,
});
export const AutomationRule = IDL.Record({
  'id' : EntityId,
  'action' : AutomationAction,
  'trigger' : AutomationTrigger,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'tenantId' : TenantId,
});
export const BackupStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Running' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Backup = IDL.Record({
  'id' : EntityId,
  'status' : BackupStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'tenantId' : TenantId,
  'backupLabel' : IDL.Text,
  'sizeBytes' : IDL.Opt(IDL.Nat),
});
export const ChannelInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'memberIds' : IDL.Vec(UserId),
  'isPublic' : IDL.Bool,
});
export const Channel = IDL.Record({
  'id' : EntityId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Text,
  'tenantId' : TenantId,
  'memberIds' : IDL.Vec(UserId),
  'isPublic' : IDL.Bool,
});
export const EscrowInput = IDL.Record({
  'title' : IDL.Text,
  'dueDate' : IDL.Opt(Timestamp),
  'description' : IDL.Text,
  'currency' : IDL.Text,
  'conditions' : IDL.Vec(IDL.Text),
  'crossLinks' : IDL.Vec(CrossLink),
  'amount' : IDL.Nat,
  'payeeId' : UserId,
});
export const RecurrenceRule = IDL.Variant({
  'Weekly' : IDL.Null,
  'None' : IDL.Null,
  'Daily' : IDL.Null,
  'Monthly' : IDL.Null,
  'Yearly' : IDL.Null,
});
export const EventInput = IDL.Record({
  'startTime' : Timestamp,
  'title' : IDL.Text,
  'endTime' : Timestamp,
  'description' : IDL.Text,
  'attendeeIds' : IDL.Vec(UserId),
  'recurrence' : RecurrenceRule,
  'crossLinks' : IDL.Vec(CrossLink),
});
export const Event = IDL.Record({
  'id' : EntityId,
  'startTime' : Timestamp,
  'title' : IDL.Text,
  'endTime' : Timestamp,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Text,
  'attendeeIds' : IDL.Vec(UserId),
  'tenantId' : TenantId,
  'recurrence' : RecurrenceRule,
  'updatedAt' : Timestamp,
  'crossLinks' : IDL.Vec(CrossLink),
});
export const NoteInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'crossLinks' : IDL.Vec(CrossLink),
});
export const Note = IDL.Record({
  'id' : EntityId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'crossLinks' : IDL.Vec(CrossLink),
});
export const ProjectInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'memberIds' : IDL.Vec(UserId),
});
export const TaskPriority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'Critical' : IDL.Null,
});
export const TaskInput = IDL.Record({
  'title' : IDL.Text,
  'assigneeId' : IDL.Opt(UserId),
  'dueDate' : IDL.Opt(Timestamp),
  'description' : IDL.Text,
  'projectId' : EntityId,
  'priority' : TaskPriority,
  'crossLinks' : IDL.Vec(CrossLink),
});
export const TaskStatus = IDL.Variant({
  'Blocked' : IDL.Null,
  'Done' : IDL.Null,
  'Todo' : IDL.Null,
  'InProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : EntityId,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'assigneeId' : IDL.Opt(UserId),
  'createdAt' : Timestamp,
  'dueDate' : IDL.Opt(Timestamp),
  'description' : IDL.Text,
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'projectId' : EntityId,
  'priority' : TaskPriority,
  'crossLinks' : IDL.Vec(CrossLink),
});
export const WalletAccount = IDL.Record({
  'id' : EntityId,
  'accountId' : IDL.Text,
  'displayName' : IDL.Text,
  'btcBalance' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'icpBalance' : IDL.Nat,
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'principalId' : IDL.Text,
});
export const WorkspaceInput = IDL.Record({ 'name' : IDL.Text });
export const Workspace = IDL.Record({
  'id' : EntityId,
  'ownerId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'tenantId' : TenantId,
});
export const Message = IDL.Record({
  'id' : EntityId,
  'content' : IDL.Text,
  'channelId' : EntityId,
  'createdAt' : Timestamp,
  'tenantId' : TenantId,
  'updatedAt' : Timestamp,
  'replyToId' : IDL.Opt(EntityId),
  'crossLinks' : IDL.Vec(CrossLink),
  'senderId' : UserId,
});
export const Role = IDL.Variant({
  'Admin' : IDL.Null,
  'Manager' : IDL.Null,
  'TeamMember' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : IDL.Text,
  'tenantId' : TenantId,
  'workspaceId' : EntityId,
});
export const AuditLog = IDL.Record({
  'id' : EntityId,
  'action' : IDL.Text,
  'userId' : UserId,
  'tenantId' : TenantId,
  'entityId' : EntityId,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
  'entityType' : IDL.Text,
});
export const PayrollStatus = IDL.Variant({
  'Paused' : IDL.Null,
  'Active' : IDL.Null,
  'Completed' : IDL.Null,
});
export const PayrollRecord = IDL.Record({
  'id' : EntityId,
  'status' : PayrollStatus,
  'period' : IDL.Text,
  'createdAt' : Timestamp,
  'tenantId' : TenantId,
  'processedAt' : IDL.Opt(Timestamp),
  'employeeId' : EntityId,
  'currency' : IDL.Text,
  'amount' : IDL.Nat,
});
export const TransactionStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'Stake' : IDL.Null,
  'Send' : IDL.Null,
  'Swap' : IDL.Null,
  'Unstake' : IDL.Null,
  'Receive' : IDL.Null,
});
export const WalletTransaction = IDL.Record({
  'id' : EntityId,
  'status' : TransactionStatus,
  'asset' : AssetType,
  'accountId' : EntityId,
  'fromAddress' : IDL.Opt(IDL.Text),
  'memo' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'tenantId' : TenantId,
  'txType' : TransactionType,
  'toAddress' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const MessageInput = IDL.Record({
  'content' : IDL.Text,
  'channelId' : EntityId,
  'replyToId' : IDL.Opt(EntityId),
  'crossLinks' : IDL.Vec(CrossLink),
});
export const UserProfileInput = IDL.Record({
  'displayName' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
  'workspaceId' : EntityId,
});

export const idlService = IDL.Service({
  'addEmployee' : IDL.Func(
      [TenantId, EmployeeInput],
      [IDL.Variant({ 'ok' : Employee, 'err' : IDL.Text })],
      [],
    ),
  'archiveProject' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : Project, 'err' : IDL.Text })],
      [],
    ),
  'cancelEscrow' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : EscrowContract, 'err' : IDL.Text })],
      [],
    ),
  'cancelRecurringPayment' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : RecurringPayment, 'err' : IDL.Text })],
      [],
    ),
  'createAutomationRule' : IDL.Func(
      [TenantId, IDL.Text, IDL.Text, AutomationTrigger, AutomationAction],
      [IDL.Variant({ 'ok' : AutomationRule, 'err' : IDL.Text })],
      [],
    ),
  'createBackup' : IDL.Func(
      [TenantId, IDL.Text],
      [IDL.Variant({ 'ok' : Backup, 'err' : IDL.Text })],
      [],
    ),
  'createChannel' : IDL.Func(
      [TenantId, ChannelInput],
      [IDL.Variant({ 'ok' : Channel, 'err' : IDL.Text })],
      [],
    ),
  'createEscrow' : IDL.Func(
      [TenantId, EscrowInput],
      [IDL.Variant({ 'ok' : EscrowContract, 'err' : IDL.Text })],
      [],
    ),
  'createEvent' : IDL.Func(
      [TenantId, EventInput],
      [IDL.Variant({ 'ok' : Event, 'err' : IDL.Text })],
      [],
    ),
  'createNote' : IDL.Func(
      [TenantId, NoteInput],
      [IDL.Variant({ 'ok' : Note, 'err' : IDL.Text })],
      [],
    ),
  'createProject' : IDL.Func(
      [TenantId, ProjectInput],
      [IDL.Variant({ 'ok' : Project, 'err' : IDL.Text })],
      [],
    ),
  'createRecurringPayment' : IDL.Func(
      [TenantId, EntityId, IDL.Text, IDL.Nat, AssetType, PayFrequency],
      [IDL.Variant({ 'ok' : RecurringPayment, 'err' : IDL.Text })],
      [],
    ),
  'createTask' : IDL.Func(
      [TenantId, TaskInput],
      [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
      [],
    ),
  'createWalletAccount' : IDL.Func(
      [TenantId, IDL.Text],
      [IDL.Variant({ 'ok' : WalletAccount, 'err' : IDL.Text })],
      [],
    ),
  'createWorkspace' : IDL.Func(
      [TenantId, WorkspaceInput],
      [IDL.Variant({ 'ok' : Workspace, 'err' : IDL.Text })],
      [],
    ),
  'deactivateEmployee' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : Employee, 'err' : IDL.Text })],
      [],
    ),
  'deleteEvent' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteMessage' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteNote' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteTask' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'disputeEscrow' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : EscrowContract, 'err' : IDL.Text })],
      [],
    ),
  'fundEscrow' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : EscrowContract, 'err' : IDL.Text })],
      [],
    ),
  'getBackup' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : Backup, 'err' : IDL.Text })],
      ['query'],
    ),
  'getChannel' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : Channel, 'err' : IDL.Text })],
      ['query'],
    ),
  'getEmployee' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : Employee, 'err' : IDL.Text })],
      ['query'],
    ),
  'getEscrow' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : EscrowContract, 'err' : IDL.Text })],
      ['query'],
    ),
  'getEvent' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : Event, 'err' : IDL.Text })],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [TenantId, EntityId, IDL.Nat, IDL.Opt(Timestamp)],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([TenantId], [IDL.Opt(UserProfile)], ['query']),
  'getMyWalletAccount' : IDL.Func(
      [TenantId],
      [IDL.Opt(WalletAccount)],
      ['query'],
    ),
  'getNote' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : Note, 'err' : IDL.Text })],
      ['query'],
    ),
  'getProject' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : Project, 'err' : IDL.Text })],
      ['query'],
    ),
  'getTask' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
      ['query'],
    ),
  'getWalletAccount' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : WalletAccount, 'err' : IDL.Text })],
      ['query'],
    ),
  'getWorkspace' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : Workspace, 'err' : IDL.Text })],
      ['query'],
    ),
  'getWorkspaceStats' : IDL.Func(
      [TenantId],
      [
        IDL.Record({
          'walletAccountCount' : IDL.Nat,
          'employeeCount' : IDL.Nat,
          'noteCount' : IDL.Nat,
          'escrowCount' : IDL.Nat,
          'projectCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'joinChannel' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : Channel, 'err' : IDL.Text })],
      [],
    ),
  'listAuditLogs' : IDL.Func(
      [TenantId, IDL.Nat],
      [IDL.Vec(AuditLog)],
      ['query'],
    ),
  'listAutomationRules' : IDL.Func(
      [TenantId],
      [IDL.Vec(AutomationRule)],
      ['query'],
    ),
  'listBackups' : IDL.Func([TenantId], [IDL.Vec(Backup)], ['query']),
  'listChannels' : IDL.Func([TenantId], [IDL.Vec(Channel)], ['query']),
  'listEmployees' : IDL.Func([TenantId], [IDL.Vec(Employee)], ['query']),
  'listEscrows' : IDL.Func([TenantId], [IDL.Vec(EscrowContract)], ['query']),
  'listEvents' : IDL.Func(
      [TenantId, Timestamp, Timestamp],
      [IDL.Vec(Event)],
      ['query'],
    ),
  'listMyEvents' : IDL.Func([TenantId], [IDL.Vec(Event)], ['query']),
  'listNotes' : IDL.Func([TenantId], [IDL.Vec(Note)], ['query']),
  'listPayrollRecords' : IDL.Func(
      [TenantId, IDL.Opt(EntityId)],
      [IDL.Vec(PayrollRecord)],
      ['query'],
    ),
  'listProfiles' : IDL.Func([TenantId], [IDL.Vec(UserProfile)], ['query']),
  'listProjects' : IDL.Func([TenantId], [IDL.Vec(Project)], ['query']),
  'listRecurringPayments' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Vec(RecurringPayment)],
      ['query'],
    ),
  'listTasks' : IDL.Func([TenantId, EntityId], [IDL.Vec(Task)], ['query']),
  'listTransactions' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Vec(WalletTransaction)],
      ['query'],
    ),
  'listWorkspaces' : IDL.Func([TenantId], [IDL.Vec(Workspace)], ['query']),
  'processPayroll' : IDL.Func(
      [TenantId, EntityId, IDL.Text],
      [IDL.Variant({ 'ok' : PayrollRecord, 'err' : IDL.Text })],
      [],
    ),
  'releaseEscrow' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : EscrowContract, 'err' : IDL.Text })],
      [],
    ),
  'searchNotes' : IDL.Func([TenantId, IDL.Text], [IDL.Vec(Note)], ['query']),
  'sendAsset' : IDL.Func(
      [TenantId, EntityId, AssetType, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : WalletTransaction, 'err' : IDL.Text })],
      [],
    ),
  'sendMessage' : IDL.Func(
      [TenantId, MessageInput],
      [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
      [],
    ),
  'toggleAutomationRule' : IDL.Func(
      [TenantId, EntityId],
      [IDL.Variant({ 'ok' : AutomationRule, 'err' : IDL.Text })],
      [],
    ),
  'updateEmployee' : IDL.Func(
      [TenantId, EntityId, EmployeeInput],
      [IDL.Variant({ 'ok' : Employee, 'err' : IDL.Text })],
      [],
    ),
  'updateEvent' : IDL.Func(
      [TenantId, EntityId, EventInput],
      [IDL.Variant({ 'ok' : Event, 'err' : IDL.Text })],
      [],
    ),
  'updateNote' : IDL.Func(
      [TenantId, EntityId, NoteInput],
      [IDL.Variant({ 'ok' : Note, 'err' : IDL.Text })],
      [],
    ),
  'updateProject' : IDL.Func(
      [TenantId, EntityId, ProjectInput],
      [IDL.Variant({ 'ok' : Project, 'err' : IDL.Text })],
      [],
    ),
  'updateTask' : IDL.Func(
      [TenantId, EntityId, TaskInput],
      [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
      [],
    ),
  'upsertProfile' : IDL.Func(
      [TenantId, UserProfileInput],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TenantId = IDL.Text;
  const UserId = IDL.Principal;
  const PayFrequency = IDL.Variant({
    'BiWeekly' : IDL.Null,
    'Weekly' : IDL.Null,
    'Quarterly' : IDL.Null,
    'Monthly' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const EmployeeInput = IDL.Record({
    'salary' : IDL.Nat,
    'userId' : UserId,
    'email' : IDL.Text,
    'currency' : IDL.Text,
    'payFrequency' : PayFrequency,
    'lastName' : IDL.Text,
    'taxRate' : IDL.Nat,
    'startDate' : Timestamp,
    'firstName' : IDL.Text,
  });
  const EntityId = IDL.Text;
  const Employee = IDL.Record({
    'id' : EntityId,
    'salary' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'tenantId' : TenantId,
    'currency' : IDL.Text,
    'payFrequency' : PayFrequency,
    'lastName' : IDL.Text,
    'taxRate' : IDL.Nat,
    'startDate' : Timestamp,
    'firstName' : IDL.Text,
  });
  const ProjectStatus = IDL.Variant({
    'OnHold' : IDL.Null,
    'Active' : IDL.Null,
    'Archived' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const CrossLink = IDL.Record({
    'linkLabel' : IDL.Text,
    'tenantId' : TenantId,
    'entityId' : EntityId,
    'entityType' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : EntityId,
    'status' : ProjectStatus,
    'ownerId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'tenantId' : TenantId,
    'updatedAt' : Timestamp,
    'memberIds' : IDL.Vec(UserId),
    'crossLinks' : IDL.Vec(CrossLink),
  });
  const EscrowStatus = IDL.Variant({
    'Disputed' : IDL.Null,
    'Released' : IDL.Null,
    'Funded' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const EscrowContract = IDL.Record({
    'id' : EntityId,
    'status' : EscrowStatus,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'dueDate' : IDL.Opt(Timestamp),
    'description' : IDL.Text,
    'tenantId' : TenantId,
    'updatedAt' : Timestamp,
    'currency' : IDL.Text,
    'conditions' : IDL.Vec(IDL.Text),
    'crossLinks' : IDL.Vec(CrossLink),
    'amount' : IDL.Nat,
    'payeeId' : UserId,
    'payerId' : UserId,
  });
  const AssetType = IDL.Variant({ 'BTC' : IDL.Null, 'ICP' : IDL.Null });
  const RecurringPayment = IDL.Record({
    'id' : EntityId,
    'asset' : AssetType,
    'accountId' : EntityId,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'tenantId' : TenantId,
    'nextRunAt' : Timestamp,
    'frequency' : PayFrequency,
    'toAddress' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const AutomationTrigger = IDL.Variant({
    'OnTaskStatusChange' : IDL.Null,
    'OnNoteCreated' : IDL.Null,
    'OnPaymentDue' : IDL.Null,
    'Scheduled' : IDL.Null,
    'OnEscrowUpdate' : IDL.Null,
    'OnEventReminder' : IDL.Null,
  });
  const AutomationAction = IDL.Variant({
    'RunPayroll' : IDL.Null,
    'CreateTask' : IDL.Null,
    'SendNotification' : IDL.Null,
    'UpdateStatus' : IDL.Null,
  });
  const AutomationRule = IDL.Record({
    'id' : EntityId,
    'action' : AutomationAction,
    'trigger' : AutomationTrigger,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'tenantId' : TenantId,
  });
  const BackupStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Running' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Backup = IDL.Record({
    'id' : EntityId,
    'status' : BackupStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'tenantId' : TenantId,
    'backupLabel' : IDL.Text,
    'sizeBytes' : IDL.Opt(IDL.Nat),
  });
  const ChannelInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'memberIds' : IDL.Vec(UserId),
    'isPublic' : IDL.Bool,
  });
  const Channel = IDL.Record({
    'id' : EntityId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Text,
    'tenantId' : TenantId,
    'memberIds' : IDL.Vec(UserId),
    'isPublic' : IDL.Bool,
  });
  const EscrowInput = IDL.Record({
    'title' : IDL.Text,
    'dueDate' : IDL.Opt(Timestamp),
    'description' : IDL.Text,
    'currency' : IDL.Text,
    'conditions' : IDL.Vec(IDL.Text),
    'crossLinks' : IDL.Vec(CrossLink),
    'amount' : IDL.Nat,
    'payeeId' : UserId,
  });
  const RecurrenceRule = IDL.Variant({
    'Weekly' : IDL.Null,
    'None' : IDL.Null,
    'Daily' : IDL.Null,
    'Monthly' : IDL.Null,
    'Yearly' : IDL.Null,
  });
  const EventInput = IDL.Record({
    'startTime' : Timestamp,
    'title' : IDL.Text,
    'endTime' : Timestamp,
    'description' : IDL.Text,
    'attendeeIds' : IDL.Vec(UserId),
    'recurrence' : RecurrenceRule,
    'crossLinks' : IDL.Vec(CrossLink),
  });
  const Event = IDL.Record({
    'id' : EntityId,
    'startTime' : Timestamp,
    'title' : IDL.Text,
    'endTime' : Timestamp,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Text,
    'attendeeIds' : IDL.Vec(UserId),
    'tenantId' : TenantId,
    'recurrence' : RecurrenceRule,
    'updatedAt' : Timestamp,
    'crossLinks' : IDL.Vec(CrossLink),
  });
  const NoteInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'crossLinks' : IDL.Vec(CrossLink),
  });
  const Note = IDL.Record({
    'id' : EntityId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'tenantId' : TenantId,
    'updatedAt' : Timestamp,
    'crossLinks' : IDL.Vec(CrossLink),
  });
  const ProjectInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'memberIds' : IDL.Vec(UserId),
  });
  const TaskPriority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Critical' : IDL.Null,
  });
  const TaskInput = IDL.Record({
    'title' : IDL.Text,
    'assigneeId' : IDL.Opt(UserId),
    'dueDate' : IDL.Opt(Timestamp),
    'description' : IDL.Text,
    'projectId' : EntityId,
    'priority' : TaskPriority,
    'crossLinks' : IDL.Vec(CrossLink),
  });
  const TaskStatus = IDL.Variant({
    'Blocked' : IDL.Null,
    'Done' : IDL.Null,
    'Todo' : IDL.Null,
    'InProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : EntityId,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'assigneeId' : IDL.Opt(UserId),
    'createdAt' : Timestamp,
    'dueDate' : IDL.Opt(Timestamp),
    'description' : IDL.Text,
    'tenantId' : TenantId,
    'updatedAt' : Timestamp,
    'projectId' : EntityId,
    'priority' : TaskPriority,
    'crossLinks' : IDL.Vec(CrossLink),
  });
  const WalletAccount = IDL.Record({
    'id' : EntityId,
    'accountId' : IDL.Text,
    'displayName' : IDL.Text,
    'btcBalance' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'icpBalance' : IDL.Nat,
    'tenantId' : TenantId,
    'updatedAt' : Timestamp,
    'principalId' : IDL.Text,
  });
  const WorkspaceInput = IDL.Record({ 'name' : IDL.Text });
  const Workspace = IDL.Record({
    'id' : EntityId,
    'ownerId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'tenantId' : TenantId,
  });
  const Message = IDL.Record({
    'id' : EntityId,
    'content' : IDL.Text,
    'channelId' : EntityId,
    'createdAt' : Timestamp,
    'tenantId' : TenantId,
    'updatedAt' : Timestamp,
    'replyToId' : IDL.Opt(EntityId),
    'crossLinks' : IDL.Vec(CrossLink),
    'senderId' : UserId,
  });
  const Role = IDL.Variant({
    'Admin' : IDL.Null,
    'Manager' : IDL.Null,
    'TeamMember' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'role' : Role,
    'email' : IDL.Text,
    'tenantId' : TenantId,
    'workspaceId' : EntityId,
  });
  const AuditLog = IDL.Record({
    'id' : EntityId,
    'action' : IDL.Text,
    'userId' : UserId,
    'tenantId' : TenantId,
    'entityId' : EntityId,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
    'entityType' : IDL.Text,
  });
  const PayrollStatus = IDL.Variant({
    'Paused' : IDL.Null,
    'Active' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const PayrollRecord = IDL.Record({
    'id' : EntityId,
    'status' : PayrollStatus,
    'period' : IDL.Text,
    'createdAt' : Timestamp,
    'tenantId' : TenantId,
    'processedAt' : IDL.Opt(Timestamp),
    'employeeId' : EntityId,
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const TransactionStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'Stake' : IDL.Null,
    'Send' : IDL.Null,
    'Swap' : IDL.Null,
    'Unstake' : IDL.Null,
    'Receive' : IDL.Null,
  });
  const WalletTransaction = IDL.Record({
    'id' : EntityId,
    'status' : TransactionStatus,
    'asset' : AssetType,
    'accountId' : EntityId,
    'fromAddress' : IDL.Opt(IDL.Text),
    'memo' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'tenantId' : TenantId,
    'txType' : TransactionType,
    'toAddress' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const MessageInput = IDL.Record({
    'content' : IDL.Text,
    'channelId' : EntityId,
    'replyToId' : IDL.Opt(EntityId),
    'crossLinks' : IDL.Vec(CrossLink),
  });
  const UserProfileInput = IDL.Record({
    'displayName' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
    'workspaceId' : EntityId,
  });
  
  return IDL.Service({
    'addEmployee' : IDL.Func(
        [TenantId, EmployeeInput],
        [IDL.Variant({ 'ok' : Employee, 'err' : IDL.Text })],
        [],
      ),
    'archiveProject' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : Project, 'err' : IDL.Text })],
        [],
      ),
    'cancelEscrow' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : EscrowContract, 'err' : IDL.Text })],
        [],
      ),
    'cancelRecurringPayment' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : RecurringPayment, 'err' : IDL.Text })],
        [],
      ),
    'createAutomationRule' : IDL.Func(
        [TenantId, IDL.Text, IDL.Text, AutomationTrigger, AutomationAction],
        [IDL.Variant({ 'ok' : AutomationRule, 'err' : IDL.Text })],
        [],
      ),
    'createBackup' : IDL.Func(
        [TenantId, IDL.Text],
        [IDL.Variant({ 'ok' : Backup, 'err' : IDL.Text })],
        [],
      ),
    'createChannel' : IDL.Func(
        [TenantId, ChannelInput],
        [IDL.Variant({ 'ok' : Channel, 'err' : IDL.Text })],
        [],
      ),
    'createEscrow' : IDL.Func(
        [TenantId, EscrowInput],
        [IDL.Variant({ 'ok' : EscrowContract, 'err' : IDL.Text })],
        [],
      ),
    'createEvent' : IDL.Func(
        [TenantId, EventInput],
        [IDL.Variant({ 'ok' : Event, 'err' : IDL.Text })],
        [],
      ),
    'createNote' : IDL.Func(
        [TenantId, NoteInput],
        [IDL.Variant({ 'ok' : Note, 'err' : IDL.Text })],
        [],
      ),
    'createProject' : IDL.Func(
        [TenantId, ProjectInput],
        [IDL.Variant({ 'ok' : Project, 'err' : IDL.Text })],
        [],
      ),
    'createRecurringPayment' : IDL.Func(
        [TenantId, EntityId, IDL.Text, IDL.Nat, AssetType, PayFrequency],
        [IDL.Variant({ 'ok' : RecurringPayment, 'err' : IDL.Text })],
        [],
      ),
    'createTask' : IDL.Func(
        [TenantId, TaskInput],
        [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
        [],
      ),
    'createWalletAccount' : IDL.Func(
        [TenantId, IDL.Text],
        [IDL.Variant({ 'ok' : WalletAccount, 'err' : IDL.Text })],
        [],
      ),
    'createWorkspace' : IDL.Func(
        [TenantId, WorkspaceInput],
        [IDL.Variant({ 'ok' : Workspace, 'err' : IDL.Text })],
        [],
      ),
    'deactivateEmployee' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : Employee, 'err' : IDL.Text })],
        [],
      ),
    'deleteEvent' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteMessage' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteNote' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteTask' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'disputeEscrow' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : EscrowContract, 'err' : IDL.Text })],
        [],
      ),
    'fundEscrow' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : EscrowContract, 'err' : IDL.Text })],
        [],
      ),
    'getBackup' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : Backup, 'err' : IDL.Text })],
        ['query'],
      ),
    'getChannel' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : Channel, 'err' : IDL.Text })],
        ['query'],
      ),
    'getEmployee' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : Employee, 'err' : IDL.Text })],
        ['query'],
      ),
    'getEscrow' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : EscrowContract, 'err' : IDL.Text })],
        ['query'],
      ),
    'getEvent' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : Event, 'err' : IDL.Text })],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [TenantId, EntityId, IDL.Nat, IDL.Opt(Timestamp)],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([TenantId], [IDL.Opt(UserProfile)], ['query']),
    'getMyWalletAccount' : IDL.Func(
        [TenantId],
        [IDL.Opt(WalletAccount)],
        ['query'],
      ),
    'getNote' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : Note, 'err' : IDL.Text })],
        ['query'],
      ),
    'getProject' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : Project, 'err' : IDL.Text })],
        ['query'],
      ),
    'getTask' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
        ['query'],
      ),
    'getWalletAccount' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : WalletAccount, 'err' : IDL.Text })],
        ['query'],
      ),
    'getWorkspace' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : Workspace, 'err' : IDL.Text })],
        ['query'],
      ),
    'getWorkspaceStats' : IDL.Func(
        [TenantId],
        [
          IDL.Record({
            'walletAccountCount' : IDL.Nat,
            'employeeCount' : IDL.Nat,
            'noteCount' : IDL.Nat,
            'escrowCount' : IDL.Nat,
            'projectCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'joinChannel' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : Channel, 'err' : IDL.Text })],
        [],
      ),
    'listAuditLogs' : IDL.Func(
        [TenantId, IDL.Nat],
        [IDL.Vec(AuditLog)],
        ['query'],
      ),
    'listAutomationRules' : IDL.Func(
        [TenantId],
        [IDL.Vec(AutomationRule)],
        ['query'],
      ),
    'listBackups' : IDL.Func([TenantId], [IDL.Vec(Backup)], ['query']),
    'listChannels' : IDL.Func([TenantId], [IDL.Vec(Channel)], ['query']),
    'listEmployees' : IDL.Func([TenantId], [IDL.Vec(Employee)], ['query']),
    'listEscrows' : IDL.Func([TenantId], [IDL.Vec(EscrowContract)], ['query']),
    'listEvents' : IDL.Func(
        [TenantId, Timestamp, Timestamp],
        [IDL.Vec(Event)],
        ['query'],
      ),
    'listMyEvents' : IDL.Func([TenantId], [IDL.Vec(Event)], ['query']),
    'listNotes' : IDL.Func([TenantId], [IDL.Vec(Note)], ['query']),
    'listPayrollRecords' : IDL.Func(
        [TenantId, IDL.Opt(EntityId)],
        [IDL.Vec(PayrollRecord)],
        ['query'],
      ),
    'listProfiles' : IDL.Func([TenantId], [IDL.Vec(UserProfile)], ['query']),
    'listProjects' : IDL.Func([TenantId], [IDL.Vec(Project)], ['query']),
    'listRecurringPayments' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Vec(RecurringPayment)],
        ['query'],
      ),
    'listTasks' : IDL.Func([TenantId, EntityId], [IDL.Vec(Task)], ['query']),
    'listTransactions' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Vec(WalletTransaction)],
        ['query'],
      ),
    'listWorkspaces' : IDL.Func([TenantId], [IDL.Vec(Workspace)], ['query']),
    'processPayroll' : IDL.Func(
        [TenantId, EntityId, IDL.Text],
        [IDL.Variant({ 'ok' : PayrollRecord, 'err' : IDL.Text })],
        [],
      ),
    'releaseEscrow' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : EscrowContract, 'err' : IDL.Text })],
        [],
      ),
    'searchNotes' : IDL.Func([TenantId, IDL.Text], [IDL.Vec(Note)], ['query']),
    'sendAsset' : IDL.Func(
        [TenantId, EntityId, AssetType, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : WalletTransaction, 'err' : IDL.Text })],
        [],
      ),
    'sendMessage' : IDL.Func(
        [TenantId, MessageInput],
        [IDL.Variant({ 'ok' : Message, 'err' : IDL.Text })],
        [],
      ),
    'toggleAutomationRule' : IDL.Func(
        [TenantId, EntityId],
        [IDL.Variant({ 'ok' : AutomationRule, 'err' : IDL.Text })],
        [],
      ),
    'updateEmployee' : IDL.Func(
        [TenantId, EntityId, EmployeeInput],
        [IDL.Variant({ 'ok' : Employee, 'err' : IDL.Text })],
        [],
      ),
    'updateEvent' : IDL.Func(
        [TenantId, EntityId, EventInput],
        [IDL.Variant({ 'ok' : Event, 'err' : IDL.Text })],
        [],
      ),
    'updateNote' : IDL.Func(
        [TenantId, EntityId, NoteInput],
        [IDL.Variant({ 'ok' : Note, 'err' : IDL.Text })],
        [],
      ),
    'updateProject' : IDL.Func(
        [TenantId, EntityId, ProjectInput],
        [IDL.Variant({ 'ok' : Project, 'err' : IDL.Text })],
        [],
      ),
    'updateTask' : IDL.Func(
        [TenantId, EntityId, TaskInput],
        [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
        [],
      ),
    'upsertProfile' : IDL.Func(
        [TenantId, UserProfileInput],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };